- name: test
  hosts: all
  become: true
  tasks:
    - name: Install agent
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        headless: false
        version: "2.2.3"
        protocol: observiq
        endpoint: http://localhost:3001
        secret_key:  "{{ lookup('env', 'OIQ_SECRET_KEY') }}"
        labels: "purpose=test,deployedby=ansible"
