---
- name: Create install directory tree
  file:
    # item is the loop value
    path: "{{ install_dir }}/{{ item }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: 0775
    # when recurse is enabled, config file mode will be set to 0775
    # which is a security risk
    recurse: false
  loop:
    - 'config'
    - 'launcher'
    - 'log'
    - 'log_agent'
    - 'manager'
    - 'manager/current'
    - 'manager/previous'
    - 'manager/previous/current'

- name: Install agent launcher
  get_url:
    url: "https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/bpagent-launcher-linux-amd64"
    dest: "{{ install_dir }}/launcher/bpagent-launcher-linux-amd64"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: 0755
  notify: "restart {{ agent_type }} agent"
  register: launcher

- name: Install agent manager
  get_url:
    url: "https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/bpagent-manager-linux-amd64"
    dest: "{{ install_dir }}/manager/current/bpagent-manager-linux-amd64"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: 0755
  notify: "restart {{ agent_type }} agent"

- name: Register plugins directory
  stat:
    path: "{{ install_dir }}/log_agent/plugins"
  register: plugin_dir

- name: Install plugins
  ansible.builtin.unarchive:
    # creates {{ install_dir }}/log_agent/plugins
    src: "https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/stanza-plugins.tar.gz"
    dest: "{{ install_dir }}/log_agent"
    remote_src: yes
  notify: "restart {{ agent_type }} agent"
  when: launcher.changed or not plugin_dir.stat.exists

# Store configuratin options as a json file, changes to
# this file will trigger an update to remote.yaml
- name: Create config/remote.json
  template: "remote.json"
    src: "remote.yaml"
    dest: "{{ install_dir }}/config/remote.yaml"
    mode: 0600
  register: remote_json

# remote.yaml is dynamically configured by observIQ cloud, so we only
# update it when there is a change to remote.json, which contains user
# configured options. If the user does not set an agent_id, updates to
# this file will cause a new agent to appear in observIQ cloud.
- name: Create config/remote.yaml
  template:
    src: "remote.yaml"
    dest: "{{ install_dir }}/config/remote.yaml"
    mode: 0600
  notify: "restart {{ agent_type }} agent"
  when: remote_json.changed

- name: Create config/logging.yaml
  template:
    src: "logging.yaml"
    dest: "{{ install_dir }}/config/logging.yaml"
    mode: 0600
  notify: "restart {{ agent_type }} agent"

- name: Create config/os.yaml
  template:
    src: "os.yaml"
    dest: "{{ install_dir }}/config/os.yaml"
    mode: 0600
  notify: "restart {{ agent_type }} agent"

- name: Create service file
  template:
    src: "observiq-agent.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: 0644
  notify:
    - reload systemctl

- name: Start observiq-agent
  service: name={{ service_name }}.service state=started enabled=yes
