---
- name: Install from amd64 rpm package
  yum:
    name: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-amd64.rpm
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "RedHat"
  - ansible_architecture == "x86_64"
  notify: "restart observiq-agent agent"

- name: Install from arm64 rpm package
  yum:
    name: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-arm64.rpm
    state: present
    disable_gpg_check: true
  when:
  - ansible_os_family == "Suse"
  - ansible_architecture == "aarch64" or ansible_architecture == "arm64"
  notify: "restart observiq-agent agent"

- name: Install from amd64 rpm package
  zypper:
    name: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-amd64.rpm
    state: present
    disable_gpg_check: true
  when: 
  - ansible_os_family == "Suse"
  - ansible_architecture == "x86_64"
  notify: "restart observiq-agent agent"

- name: Install from arm64 rpm package
  zypper:
    name: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-arm64.rpm
    state: present
    disable_gpg_check: true
  when:
  - ansible_os_family == "Suse"
  - ansible_architecture == "aarch64" or ansible_architecture == "arm64"
  notify: "restart observiq-agent agent"

- name: Install from amd64 deb package
  apt:
    deb: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-amd64.deb
    state: present
  when: 
  - ansible_os_family == 'Debian'
  - ansible_architecture == "x86_64"
  notify: "restart observiq-agent agent"

- name: Install from arm64 deb package
  apt:
    deb: https://storage.googleapis.com/observiq-cloud/observiq-agent/{{ version }}/artifacts/observiq-agent-{{ version }}-linux-arm64.deb
    state: present
  when: 
  - ansible_os_family == 'Debian'
  - ansible_architecture == "aarch64" or ansible_architecture == "arm64"
  notify: "restart observiq-agent agent"

# Store configuration options as a json file, changes to
# this file will trigger an update to manager.yaml. If no
# changes are made, manager.yaml will not be changed. This
# allows a remote platform to modify manager.yaml without
# risk of Ansible reverting the changes.
- name: Create config/manager.json
  template:
    src: "manager.json.tmpl"
    dest: "{{ install_dir }}/config/manager.json"
    mode: 0640
  register: remote_json
  notify: "create config/manager.yaml"

