---
- name: "restart observiq-agent agent"
  systemd:
    name: "observiq-agent.service"
    state: restarted
    daemon_reload: true
    enabled: yes

# manager.yaml is dynamically configured by remote platforms when not in headless
# mode, so we only update it when there is a change to manager.json, which contains 
# user configured options. If the user does not set an agent_id, updates to
# this file will cause a new agent to appear in observIQ cloud.
- name: "create config/manager.yaml"
  template:
    src: "manager.yaml"
    dest: "{{ install_dir }}/config/manager.yaml"
    mode: 0640
  notify: "restart observiq-agent agent"
