---
# This file is the central configuration entrypoint for Molecule. With this file, you can configure each tool that Molecule will employ when testing the role.
dependency:
  name: galaxy
driver:
  name: delegated
  gcp_service_account_key: ${GOOGLE_APPLICATION_CREDENTIALS}
  gcp_project_id: ${GCP_PROJECT_ID}
  ssh_user: ${SSH_USER}
  zone: us-east1-b
  region: us-east1
lint: |
  set -e
  ansible-lint
platforms:
  - name: "centos-7-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/centos-cloud/global/images/family/centos-7
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - centos
  - name: "centos-8-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/centos-cloud/global/images/family/centos-8
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - centos
  - name: "rhel-7-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/rhel-cloud/global/images/family/rhel-7
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - rhel
  - name: "rhel-8-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/rhel-cloud/global/images/family/rhel-8
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - rhel
  - name: "ubuntu-1604-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - ubuntu
  - name: "ubuntu-1804-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - ubuntu
  - name: "ubuntu-2004-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - ubuntu
  - name: "debian-9-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/debian-cloud/global/images/family/debian-9
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - debian
  - name: "debian-10-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/debian-cloud/global/images/family/debian-10
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - debian
  - name: "sles-12-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/suse-cloud/global/images/family/sles-12
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - sles
  - name: "sles-15-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
    image_family: projects/suse-cloud/global/images/family/sles-15
    machine_type: e2-small
    size_gb: 40
    groups:
      - linux
      - sles
  #- name: "windows-2016-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
  #  image_family: projects/windows-cloud/global/images/family/windows-2016
  #  machine_type: e2-small
  #  size_gb: 80
  #  groups:
  #    - windows
  #    - windows-2016
  #- name: "windows-2019-${MOLECULE_SCENARIO_NAME}-${GIT_REV}"
  #  image_family: projects/windows-cloud/global/images/family/windows-2019
  #  machine_type: e2-small
  #  size_gb: 80
  #  groups:
  #    - windows
  #    - windows-2019
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
provisioner:
  name: ansible
  inventory:
    group_vars:
      linux:
        ansible_ssh_private_key_file: ${SSH_KEY_FILE}
      # windows is not implemented but may be supported in the future
      #windows:
      #  ansible_become: false
      #  ansible_winrm_server_cert_validation: ignore
      #windows-2016:
      #  ansible_password: '"${WIN_2016_PW}"'
      #windows-2019:
      #  ansible_password: '"${WIN_2019_PW}"'
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: ansible