---
# Remove the agent in case the test failed in between installation and uninstallation steps.
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Uninstall agent
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') }}"
        package_state: absent
        version: "{{ lookup('env', 'VERSION') }}"
        secret_key: "" # Not required for uninstall
