---
# This playbook calls the role. Molecule will invoke this playbook with ansible-playbook and run it against an instance created by the driver.
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Install agent
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') }}"
        package_state: present
        version: "{{ lookup('env', 'VERSION') }}"
        secret_key: "{{ lookup('env', 'SECRET_KEY') }}"