---
# Verify the state of the VM after the role has finished executing.
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Call Linux specific playbook
      include_tasks: verify_linux.yml
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') | default('monitoring', True) }}"
      when: ansible_os_family in ['Debian', 'RedHat', 'Suse']