---
- name: Include vars
  include_vars:
    file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/vars/main.yml"

- name: Stat remote.yaml
  stat:
    path: "/opt/observiq-agent/config/remote.yaml"
  register: result
- name: Assert remote.yaml exists
  assert:
    that: result.stat.exists

- name: Stat remote.json
  stat:
    path: "/opt/observiq-agent/config/remote.json"
  register: result
- name: Assert remote.json exists
  assert:
    that: result.stat.exists

- name: Stat os.yaml
  stat:
    path: "/opt/observiq-agent/config/os.yaml"
  register: result
- name: Assert os.yaml exists
  assert:
    that: result.stat.exists

- name: Stat logging.yaml
  stat:
    path: "/opt/observiq-agent/config/logging.yaml"
  register: result
- name: Assert logging.yaml exists
  assert:
    that: result.stat.exists
  
- name: Stat launcher binary
  stat:
    path: "/opt/observiq-agent/launcher/bpagent-launcher-linux-amd64"
  register: result
- name: Assert bpagent-launcher-linux-amd64 exists
  assert:
    that: result.stat.exists

- name: Stat manager binary
  stat:
    path: "/opt/observiq-agent/manager/current/bpagent-manager-linux-amd64"
  register: result
- name: Assert bpagent-manager-linux-amd64 exists
  assert:
    that: result.stat.exists

- name: Ensure the agent is running
  service:
    name: "observiq-agent.service"
    state: started
  register: result
- name: Assert the agent was already running
  assert:
    that: result.changed == false