name: Integration Tests
on: 
  push:
    branches:
      - master
  pull_request:
jobs:
  integration:
    name: Molecule
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Install Gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache Pip modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # Cache will reset when requirements.txt is updated
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install Pip Modules.
        run: |
          pip install -r requirements.txt
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Run Molecule tests.
        run: make test

      - name: Cleanup test instances
        run: make clean
        if: ${{ always() }}